AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  BookmarksChatBotSnsTopicArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: BookmarksChatBotSnsTopicArn

  BookmarksToolsLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: BookmarksToolsLayerArn

  TwitterLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: TwitterLayerArn

  JinjaLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: JinjaLayerArn

  KmsKeyId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: KmsKeyId

  Environ:
    Type: AWS::SSM::Parameter::Value<String>
    Default: Environ

  ArticlesTableName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ArticlesTableName

  ArticlesTableStreamArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ArticlesTableStreamArn

  StageName:
    Type: String
    Default: v1

Globals:
  Function:
    Runtime: python3.7
    Timeout: 30
    MemorySize: 256
    AutoPublishAlias: !Ref Environ
    Environment:
      Variables:
        AWS_ENV: !Ref Environ
        BOOKMARKS_USER_ID: C345859B-0C0F-45FA-AFF9-C480E34F0F36
        KMS_KEY_ID: !Ref KmsKeyId
        ARTICLES_TABLE_NAME: !Ref ArticlesTableName
    Layers:
      - !Ref BookmarksToolsLayerArn

Resources:
  TweetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/tweet
      Handler: index.handler
      Policies:
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:Encrypt
              Resource:
                - "*"
      Layers:
        - !Ref TwitterLayerArn
      Events:
        Insert:
          Type: DynamoDB
          Properties:
            Stream: !Ref ArticlesTableStreamArn
            StartingPosition: LATEST
            BatchSize: 1

  TweetLogResource:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log_resources.yml
      Parameters:
        FunctionName: !Ref TweetFunction
        AlartActionTopicArn: !Ref BookmarksChatBotSnsTopicArn
